name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Test and Upload Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test with coverage
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/profile.out
        fail_ci_if_error: true

    - name: Get the current tag or set default
      id: tag-version
      run: |
        TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "untagged")
        echo "TAG_VERSION=$TAG_VERSION"
        echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

    - name: Update badge
      run: |
        sed -i "s/old-version/${{ env.TAG_VERSION }}/g" README.md

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if ! git diff --quiet; then
          git add README.md
          git commit -am "Update badge version to ${{ env.TAG_VERSION }}"
          git push
        else
          echo "No changes to commit"
        fi
