name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Test and Upload Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test with coverage
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/profile.out
        fail_ci_if_error: true

    - name: Get the current tag
      id: tag-version
      run: echo "TAG_VERSION=$(git describe --tags)" >> $GITHUB_ENV

    - name: Update badge
      run: |
        sed -i "s/old-version/${{ env.TAG_VERSION }}/g" README.md

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update badge version to ${{ env.TAG_VERSION }}"
        git push
