name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Test and Upload Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Test with coverage
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/profile.out
        fail_ci_if_error: true
