name: Code Coverage

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Test and Upload Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags

    - name: Test with coverage
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/profile.out
        fail_ci_if_error: true

    - name: Get the current tag or set default
      id: tag-version
      run: |
        TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "untagged")
        echo "TAG_VERSION=$TAG_VERSION"
        echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

    - name: Read current version in README
      id: read-version
      run: |
        CURRENT_VERSION=$(grep -o 'version-[0-9]*\.[0-9]*\.[0-9]*' README.md | head -n 1 | cut -d '-' -f 2)
        echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
        echo "Current version in README is ${CURRENT_VERSION}"

    - name: Update badge
      run: |
        if [[ "$OSTYPE" == "darwin"* ]]; then
          # macOS
          sed -i '' "s/${{ env.CURRENT_VERSION }}/${{ env.TAG_VERSION }}/g" README.md
        else
          # Linux and others
          sed -i "s/${{ env.CURRENT_VERSION }}/${{ env.TAG_VERSION }}/g" README.md
        fi
        echo "Badge updated in README with ${TAG_VERSION} from ${CURRENT_VERSION}"

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if ! git diff --quiet; then
          git add README.md
          git commit -am "Update badge version to ${{ env.TAG_VERSION }}"
          git push
        else
          echo "No changes to commit"
        fi
